
name: Build Windows Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Install Playwright and browsers
      run: |
        python -m playwright install
        python -m playwright install chromium
        python -m playwright install-deps

    - name: List Browser Path
      run: |
        $browserPath = "$env:USERPROFILE\.cache\ms-playwright"
        Write-Host "Browser path: $browserPath"
        if (Test-Path $browserPath) {
            Get-ChildItem $browserPath -Recurse | Where-Object { $_.PSIsContainer } | ForEach-Object { Write-Host $_.FullName }
        }

    - name: Prepare Browser Files
      run: |
        New-Item -Path ".\browser_data" -ItemType Directory -Force
        Copy-Item -Path "$env:USERPROFILE\.cache\ms-playwright\*" -Destination ".\browser_data" -Recurse -Force
        Get-ChildItem ".\browser_data" -Recurse | Where-Object { $_.PSIsContainer } | ForEach-Object { Write-Host $_.FullName }

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed `
          --add-data "bills_counter;bills_counter" `
          --add-data "browser_data;playwright/.cache/ms-playwright" `
          --hidden-import playwright `
          --hidden-import playwright.async_api `
          --collect-all playwright `
          --icon icon.ico `
          main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe