
name: Build Windows Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Install Playwright
      run: |
        python -m playwright install
        python -m playwright install-deps
        python -m playwright install chromium

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ms-playwright/
          %USERPROFILE%/.cache/ms-playwright/
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Verify Playwright Installation
      run: |
        python -c "from playwright.sync_api import sync_playwright; playwright = sync_playwright().start(); browser = playwright.chromium.launch(); browser.close(); playwright.stop()"

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed ^
          --add-data "bills_counter;bills_counter" ^
          --add-data "%USERPROFILE%/.cache/ms-playwright;playwright/.cache/ms-playwright" ^
          --hidden-import playwright ^
          --hidden-import playwright.async_api ^
          --collect-all playwright ^
          --icon icon.ico ^
          main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe
