name: Build Windows Application

on:
  push:
    branches: [ master ]        # Trigger on pushes to the main branch
  pull_request:
    branches: [ master ]        # Trigger on pull requests to the main branch

jobs:
  build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            %LOCALAPPDATA%\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          playwright install

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed \
            --icon icon.ico \
            main.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            dist\*.exe

      - name: Clean up
        run: |
          rmdir /S /Q build
          rmdir /S /Q dist
          del /Q *.spec
          del /Q icon.ico

